services:

  backend:
    container_name: kungfujew_backend
    image: kungfujew-backend:latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-admin}@mongodb:27017/${MONGO_INITDB_DATABASE:-kungfujew}?authSource=admin
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      NODE_ENV: ${NODE_ENV}

      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
    depends_on:
      - mongodb
      - redis-stack
    networks:
      - blog_network